version: '3.9'
services:
  ekg-train:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TORCH_TAG: '2.4.0-rocm6.1' # <-- adjust if your ROCm differs
    image: ekgclf:rocm
    container_name: ekgclf_train
    working_dir: /workspace
    # Mount local workspace so you can edit live
    volumes:
      - ./:/workspace
      - ./mlruns:/workspace/mlruns # if using MLflow local
      - ./data:/workspace/data # your datasets
      - ./checkpoints:/workspace/checkpoints
      - ./reports:/workspace/reports
    # ROCm devices
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - 'video'
      - 'render'
    ipc: host
    environment:
      # Poetry sends installs to base site-packages (set in Dockerfile), so just run:
      - PYTHONUNBUFFERED=1
      - HIP_VISIBLE_DEVICES=0
      - ROCR_VISIBLE_DEVICES=0
      # Optional: MLflow
      - MLFLOW_TRACKING_URI=file:/workspace/mlruns
    command: >
      bash -lc "
        poetry run python -c 'import torch; 
          print(\"CUDA avail:\", torch.cuda.is_available()); 
          print(\"HIP:\", getattr(torch.version, \"hip\", None)); 
          print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else \"no-gpu\")' &&
        poetry run python src/ekgclf/train.py
      "
