paths:
  raw_dir: data/raw
  interim_dir: data/interim
  processed_dir: data/processed
  reports_dir: reports
dataset:
  name: ptbxl
  resample_hz: 500
  bandpass:
    low_hz: 0.5
    high_hz: 40.0
    order: 4
  zscore: true
  leads_expected: 12
  patient_split_seed: 1337
  splits:
    train: 0.7
    val: 0.15
    test: 0.15
augmentation:
  enabled: true
  jitter_std: 0.01
  scale_std: 0.1
  time_warp_max_pct: 0.05
input_length_sec: 10
mitbih:
  use_for_rhythm_generalization: true
